FROM contenedoresdesafiotripulacionesg3.azurecr.io/alpinesecuredesafio:latest

ENV APP_PORT=5173

WORKDIR /app/client

COPY . .

RUN npm install

RUN npm run build

EXPOSE $APP_PORT

CMD ["sh", "-c", "npm run dev -- --port $APP_PORT --host 0.0.0.0"]